# Generated by Django 4.0.3 on 2022-04-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=200)),
                ('smtp_port', models.IntegerField()),
                ('email_login', models.CharField(max_length=200)),
                ('email_pass', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('email_from', models.CharField(max_length=128)),
                ('email_to', models.EmailField(max_length=128)),
                ('email_subject', models.CharField(max_length=128)),
                ('email_text', models.TextField()),
                ('week_monday', models.BooleanField()),
                ('server_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.emailsetings')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('template_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.maintemplate')),
            ],
        ),
    ]
