# Generated by Django 4.0.4 on 2022-04-23 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintemplate',
            name='email_end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintemplate',
            name='email_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintemplate',
            name='week_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintemplate',
            name='week_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintemplate',
            name='week_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintemplate',
            name='week_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintemplate',
            name='week_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintemplate',
            name='week_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintemplate',
            name='week_monday',
            field=models.BooleanField(default=False),
        ),
    ]
